version: 0.1

hotword: resources/snowboy_model/Sory.pmdl 

hotword2: resources/snowboy_model/stopp.pmdl

log_level: INFO

azure_key: **REMOVED**

netease_api_url: http://localhost:3000

netease_email: **REMOVED**

netease_password_md5 : **REMOVED**
